### ISSUE TITLE
vscode plugin and LS have different min version for NPM and node

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-language-server#100]
https://github.com/ansible/ansible-language-server/blob/0d043fd8719179266813f67ed583337eb6063035/package.json#L27

**Comment by webknjaz** [comment]
Closing per above.

**Comment by ganeshrn** [comment]
@ssbarnea It is extremely annoying to set up dev environment on OS that doesn't have ` "node": ">=12.0", ` especially if the extension is working with the vscode version installed on the OS. It is an unnecessary overhead to mandate users to install a different node version than what vscode is using.

**Comment by ganeshrn** [comment]
Couldn't find a minimum version of npm for typescript language server implementation from this list https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by webknjaz** [comment]
@ganeshrn it's not for users but for the devs. Users use the NodeJS version that is vendored within a specific version of VS Code.

**Comment by ganeshrn** [comment]
@webknjaz Yes I am talking about devs itself. I don’t see a reason to enforce different node/npm version mandates which are different from vscode itself running on the system.

**Comment by webknjaz** [comment]
It's never the same nodejs instance that VS Code ships. And different VS Code versions may ship different Node JS inside. But there's no VS Code using NodeJS older than v12. This is why we have a matrix of supported versions.

As for Npm, it's absolutely unrelated to VS Code (as in, not related in any way imaginable). v7 was necessary for the lockfile consistency IIRC so that we avoid conflicts when one person has a really old npm that produces a lockfile in the deprecated format and everyone else use the schema for v2 resulting in constant full rewrites of the file on each commit (and possibly CI failures).

**Comment by webknjaz** [comment]
We've triaged this issue on the call and nobody could understand what could be annoying about a one-time setup.

**Comment by ssbarnea** [comment]
Closing as I think it was misunderstanding.
